@PromptSharp.Api_HostAddress = http://localhost:5042

GET {{PromptSharp.Api_HostAddress}}/health/live
Accept: application/json

###

GET {{PromptSharp.Api_HostAddress}}/api/v1/suggestions
Accept: application/json

###
