@PromptSharp.Api_HostAddress = https://localhost:5001

GET {{PromptSharp.Api_HostAddress}}/health/live

###

GET {{PromptSharp.Api_HostAddress}}/openapi/v1.json

###

GET {{PromptSharp.Api_HostAddress}}/api/v1/tutorials
Accept: application/json
