export const routes = {
  home: '/',
  catalog: '/tutorials',
  tutorialDetail: (slug = 'build-dotnet-api-with-clean-architecture') => `/tutorials/${slug}`,
  category: (slug = 'dotnet') => `/categories/${slug}`,
  tag: (slug = 'azure') => `/tags/${slug}`,
  search: (query = 'clean architecture') => `/search?q=${encodeURIComponent(query)}`,
  about: '/about',
  contact: '/contact',
  signIn: '/sign-in',
  oauthCallback: '/auth/callback?code=e2e-code&state=e2e-state',
  accessDenied: '/access-denied',
  profile: '/me/profile',
  progressBookmarks: '/me/progress',
  adminDashboard: '/admin',
  adminTutorialList: '/admin/tutorials',
  tutorialEditorNew: '/admin/tutorials/new',
  tutorialEditorEdit: (id = '11111111-1111-1111-1111-111111111111') => `/admin/tutorials/${id}/edit`,
  stepEditor: (
    tutorialId = '11111111-1111-1111-1111-111111111111',
    stepId = '22222222-2222-2222-2222-222222222222',
  ) => `/admin/tutorials/${tutorialId}/steps/${stepId}`,
  taxonomy: '/admin/taxonomy',
  mediaLibrary: '/admin/media',
  userRoles: '/admin/users',
  auditLog: '/admin/audit-log',
  notFound: '/definitely-not-a-real-prompt-sharp-route',
} as const;
