import { Routes } from '@angular/router';
import {
  AboutPage,
  AccessDeniedPage,
  AdminAuditLogPage,
  AdminDashboardPage,
  AdminMediaPage,
  AdminShell,
  AdminTaxonomyPage,
  AdminTutorialEditorPage,
  AdminTutorialListPage,
  AdminUsersPage,
  CatalogPage,
  CategoryPage,
  ContactCard,
  ErrorPage,
  HomePage,
  NotificationsGalleryPage,
  OauthCallbackPage,
  OauthConsentPage,
  ProfilePage,
  ProgressPage,
  PublicShell,
  SearchPage,
  SignInPage,
  TutorialDetailPage,
} from 'domain';
import { confirmTutorialEditorNavigation, requireAdmin, requireUser } from './auth-guards';

export const routes: Routes = [
  {
    path: '',
    component: PublicShell,
    children: [
      { path: '', component: HomePage },
      { path: 'tutorials', component: CatalogPage },
      { path: 'catalog', redirectTo: 'tutorials', pathMatch: 'full' },
      { path: 'categories/:slug', component: CategoryPage },
      { path: 'category/:slug', redirectTo: 'categories/:slug' },
      { path: 'tags/:slug', component: CategoryPage },
      { path: 'search', component: SearchPage },
      { path: 'tutorials/:slug', component: TutorialDetailPage },
      { path: 'about', component: AboutPage },
      { path: 'contact', component: ContactCard },
      { path: 'me/profile', component: ProfilePage, canActivate: [requireUser] },
      { path: 'profile', redirectTo: 'me/profile', pathMatch: 'full' },
      { path: 'me/progress', component: ProgressPage, canActivate: [requireUser] },
      { path: 'progress', redirectTo: 'me/progress', pathMatch: 'full' },
      { path: 'sign-in', component: SignInPage, data: { minimalShell: true } },
      { path: 'signin', redirectTo: 'sign-in', pathMatch: 'full' },
      { path: 'auth/callback', component: OauthCallbackPage, data: { hideFooter: true } },
      { path: 'oauth/callback', redirectTo: 'auth/callback', pathMatch: 'full' },
      { path: 'auth/consent', component: OauthConsentPage, data: { hideFooter: true } },
      { path: 'oauth/consent', redirectTo: 'auth/consent', pathMatch: 'full' },
      { path: 'access-denied', component: AccessDeniedPage, data: { hideFooter: true } },
      { path: 'notifications', component: NotificationsGalleryPage },
    ],
  },
  {
    path: 'admin',
    component: AdminShell,
    canActivate: [requireAdmin],
    children: [
      { path: '', component: AdminDashboardPage },
      { path: 'tutorials', component: AdminTutorialListPage },
      {
        path: 'tutorials/new',
        component: AdminTutorialEditorPage,
        canDeactivate: [confirmTutorialEditorNavigation],
      },
      {
        path: 'tutorials/:id/edit',
        component: AdminTutorialEditorPage,
        canDeactivate: [confirmTutorialEditorNavigation],
      },
      {
        path: 'tutorials/:id/steps/:stepId',
        component: AdminTutorialEditorPage,
        canDeactivate: [confirmTutorialEditorNavigation],
      },
      { path: 'tutorials/:id', redirectTo: 'tutorials/:id/edit' },
      { path: 'categories', component: AdminTaxonomyPage },
      { path: 'taxonomy', redirectTo: 'categories', pathMatch: 'full' },
      { path: 'media', component: AdminMediaPage },
      { path: 'users', component: AdminUsersPage },
      { path: 'audit-log', component: AdminAuditLogPage },
      { path: 'audit', redirectTo: 'audit-log', pathMatch: 'full' },
      { path: 'notifications', component: NotificationsGalleryPage },
    ],
  },
  { path: '**', component: ErrorPage },
];
